name: Sync TEST with develop
on:
  push:
    branches:
      - 'develop'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge develop -> TEST
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: TEST
          github_token: ${{ secrets.GITHUB_TOKEN }}
